### ISSUE TITLE
Program returns 0 when "properties" file missing

### ISSUE THREAD

**Issue by SHuang-Broad** [jyhehir/mobster#15]
In stead, the program should throw an exception, or have return status not 0.

**Comment by jyhehir** [comment]
Good point. Thanks for letting me know. Do you feel happy making a pull request? Otherwise I can take a look.

**Comment by SHuang-Broad** [comment]
I should be able to do it, maybe not today but this week.
Also,  an other unrelated question: for how long should I expect a run to take on a WGS bam with ~30X coverage?

Thanks for the quick reply!
