### ISSUE TITLE
Problem using Mobster

### ISSUE THREAD

**Issue by meboussaha** [jyhehir/mobster#32]
Dear Sir,
I have been using Mobster (MobileInsertions-1.0-SNAPSHOT.jar) to study TEs in cattle WGS. Today and with the availability of a new cattle reference genome we have realigned all our data against this new reference genome using the bwa-mem aligner. Unfortunately we are getting an error when executing the same pipeline (with MobileInsertions-1.0-SNAPSHOT.jar). Here is a screen shot of the rror. Any help?
Thaks in advance
Mekki
![mobster_error](https://user-images.githubusercontent.com/56909190/67772187-eacf5380-fa59-11e9-98a5-e3cf1829e82b.png)

**Comment by jyhehir** [comment]
Hi,
Can you please confirm if the data is paired-end?And if you are able to download an built it yourself?
Regards,Jayne
    On Tuesday, 29 October 2019, 02:39:45 pm GMT+1, meboussaha <notifications@github.com> wrote:  
 
 
Dear Sir,
I have been using Mobster (MobileInsertions-1.0-SNAPSHOT.jar) to study TEs in cattle WGS. Today and with the availability of a new cattle reference genome we have realigned all our data against this new reference genome using the bwa-mem aligner. Unfortunately we are getting an error when executing the same pipeline (with MobileInsertions-1.0-SNAPSHOT.jar). Here is a screen shot of the rror. Any help?
Thaks in advance
Mekki

**Comment by jyhehir** [comment]
Dear Mekki,
I have just cloned the repository to double check. After cloning, and running the install.sh I would expect that you generate a jar file in the target directory which is called MobileInsertions-0.2.4.1.jar
This version of Mobster has support for bwa_mem, which I assume you are using as aligner?Alternatively you can try running picard tools standalone on your bam to confirm that the insert size can be computed.
Regards,Jayne
    On Thursday, 31 October 2019, 05:48:03 pm GMT+1, meboussaha <notifications@github.com> wrote:  
 
 Dear Sir,
Yes the data is paired-end and its our bioinformatics facility that succesfully downloaded the mobster-0.2.4.1 version. I copied the «MobileInsertions-1.0-SNAPSHOT.jar » in the target directory.
Regards
Mekki

De : jyhehir <notifications@github.com>
Envoyé : jeudi 31 octobre 2019 16:19
À : jyhehir/mobster <mobster@noreply.github.com>
Cc : Mekki Boussaha <mekki.boussaha@inra.fr>; Author <author@noreply.github.com>
Objet : Re: [jyhehir/mobster] Problem using Mobster (#32)

Hi,
Can you please confirm if the data is paired-end?And if you are able to download an built it yourself?
Regards,Jayne
On Tuesday, 29 October 2019, 02:39:45 pm GMT+1, meboussaha <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Sir,
I have been using Mobster (MobileInsertions-1.0-SNAPSHOT.jar) to study TEs in cattle WGS. Today and with the availability of a new cattle reference genome we have realigned all our data against this new reference genome using the bwa-mem aligner. Unfortunately we are getting an error when executing the same pipeline (with MobileInsertions-1.0-SNAPSHOT.jar). Here is a screen shot of the rror. Any help?
Thaks in advance
Mekki

**Comment by meboussaha** [comment]
Hi,
Thanks a ot for your help. I solved the problem recently by using the MobileInsertions-0.2.4.1.jar and the option bwa-mem.
Regards
Mekki

De : jyhehir <notifications@github.com>
Envoyé : mardi 5 novembre 2019 16:18
À : jyhehir/mobster <mobster@noreply.github.com>
Cc : Mekki Boussaha <mekki.boussaha@inra.fr>; Author <author@noreply.github.com>
Objet : Re: [jyhehir/mobster] Problem using Mobster (#32)

Dear Mekki,
I have just cloned the repository to double check. After cloning, and running the install.sh I would expect that you generate a jar file in the target directory which is called MobileInsertions-0.2.4.1.jar
This version of Mobster has support for bwa_mem, which I assume you are using as aligner?Alternatively you can try running picard tools standalone on your bam to confirm that the insert size can be computed.
Regards,Jayne
On Thursday, 31 October 2019, 05:48:03 pm GMT+1, meboussaha <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Sir,
Yes the data is paired-end and its our bioinformatics facility that succesfully downloaded the mobster-0.2.4.1 version. I copied the «MobileInsertions-1.0-SNAPSHOT.jar » in the target directory.
Regards
Mekki

De : jyhehir <notifications@github.com<mailto:notifications@github.com>>
Envoyé : jeudi 31 octobre 2019 16:19
À : jyhehir/mobster <mobster@noreply.github.com<mailto:mobster@noreply.github.com>>
Cc : Mekki Boussaha <mekki.boussaha@inra.fr<mailto:mekki.boussaha@inra.fr>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [jyhehir/mobster] Problem using Mobster (#32)

Hi,
Can you please confirm if the data is paired-end?And if you are able to download an built it yourself?
Regards,Jayne
On Tuesday, 29 October 2019, 02:39:45 pm GMT+1, meboussaha <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>> wrote:


Dear Sir,
I have been using Mobster (MobileInsertions-1.0-SNAPSHOT.jar) to study TEs in cattle WGS. Today and with the availability of a new cattle reference genome we have realigned all our data against this new reference genome using the bwa-mem aligner. Unfortunately we are getting an error when executing the same pipeline (with MobileInsertions-1.0-SNAPSHOT.jar). Here is a screen shot of the rror. Any help?
Thaks in advance
Mekki
