### ISSUE TITLE
How to make REPEATMASK_FILE?

### ISSUE THREAD

**Issue by npaulat** [jyhehir/mobster#33]
Hello,

I am trying to run Mobster on my own data, and I would like to know what the required format of the REPEATMASK_FILE in the Mobster.properties? I looked at the example ../resources/repmask/hg19_alul1svaerv.rpmsk file, and I am unfamiliar with the format and the file extension, as it looks similar to, but not the same as a RepeatMasker .fa.out file. Could you please clarify? If this is an older output format from RepeatMasker, will Mobster accept the newer format, or how should this file be made?

Thank you,
Nikki

**Comment by jyhehir** [comment]
Dear Nikki,
Thanks for trying Mobster. Indeed I have not updated the repeatmask files recently.These can be directly downloaded from the UCSC. via the table browser https://genome.ucsc.edu/cgi-bin/hgTables
select the genome buildgroup = repeatsthen add a custom filter
repFamily = 'Alu' OR repFamily = 'L1' OR repName like 'HERV%' OR repFamily = 'SVA'

Regards,Jayne
    On Wednesday, 6 November 2019, 12:39:54 am GMT+1, npaulat <notifications@github.com> wrote:  
 
 
Hello,

I am trying to run Mobster on my own data, and I would like to know what the required format of the REPEATMASK_FILE in the Mobster.properties? I looked at the example ../resources/repmask/hg19_alul1svaerv.rpmsk file, and I am unfamiliar with the format and the file extension, as it looks similar to, but not the same as a RepeatMasker .fa.out file. Could you please clarify? If this is an older output format from RepeatMasker, will Mobster accept the newer format, or how should this file be made?

Thank you,
Nikki
