### ISSUE TITLE
Test Run Error

### ISSUE THREAD

**Issue by sph17** [jyhehir/mobster#40]
I'm trying to run the test file with Mobster but am getting the following error. I don't see any TestSample files listed in the directory

```
`java -Xmx8G -jar ./target/MobileInsertions-0.2.4.1.jar \
    -properties ./target/Mobster.properties \
    -out TestSample

0 [main] ERROR Mobster  - TestSample_insertstats (No such file or directory)`
```

**Comment by jyhehir** [comment]
do you have 
test_data/chr12_wgs_3000ins_100excl_10x_bwadef.bam

this file is quite large and requires 
git lfs for cloning





On Monday, 22 June 2020, 08:37:39 pm GMT+2, Stephanie Hao <notifications@github.com> wrote: 







I'm trying to run the test file with Mobster but am getting the following error. I don't see any TestSample files listed in the directory

java -Xmx8G -jar ./target/MobileInsertions-0.2.4.1.jar \ -properties ./target/Mobster.properties \ -out TestSample 0 [main] ERROR Mobster - TestSample_insertstats (No such file or directory)
