### ISSUE TITLE
How can I find source elements?

### ISSUE THREAD

**Issue by kaanokay** [jyhehir/mobster#41]
Hi,

I obtained mobster outputs with no issues.

I am wondering that how can I find the source element causing transposable insertion? Mobster outputs have no information about that. Namely, I want to find that inserted transposable elements coming from where or originated from which transposable element?

Thanks.

**Comment by jyhehir** [comment]
Hi Kaan,

This is sometimes not 100% clear and depends a little on how long the reads are. At this point we only include the super family in the predictions.txt. But individual reads that map to the mobiome, and hence a mei can be extracted from the intermediate file (mobster.out_mappedpotentials.bam).

Regards,
Jayne

**Comment by kaanokay** [comment]
Hi Jayne,

Thanks for your detailed response. I will try it.

Best regards.
