### ISSUE TITLE
Chromosomal mapping issue

### ISSUE THREAD

**Issue by kaanokay** [jyhehir/mobster#44]
Hi,

When I completed transposable calling using Mobster, realized that several samples with female gender had chromosome Y-mapped transposable insertions. As you know, it's not impossible but very rare. In addition to Mobster, I used a different transposable caller tool but encountered the same issue.

Did you encounter such a situation like mine before?

I am wondering the reason for that. Do you have any comments on my situation?

Best wishes.

**Comment by jyhehir** [comment]
Hi, 
The first thing that pops into my mind is the pseudo autosomal regions on chrX have a prediction, which then duplicates itself due to multi mapping on chrY. Do you see anything in the data which might support that concept?

Regards,
Jayne

**Comment by kaanokay** [comment]
@jyhehir ,

Thanks for your reply. I explored it. Chromosomal-assignment of specific insertions is based on reference-genome (it could be female or male). Another reason for that is related to pseudo-autosomal regions as you estimated. I took answers and am convinced.

Thanks for your help.

Best.
