### ISSUE TITLE
How to run mobster

### ISSUE THREAD

**Issue by johanneskoester** [jyhehir/mobster#5]
Dear @jyhehir,
I am now trying to integrate mobster into our workflow, but I cannot find documentation how to run it. I have tried:
```
mobster -in ../data/LP6005615-DNA_G10.reheader.sorted.dedup.chr22.bam -out results/mobster/LP6005615-DNA_G10 -sn LP6005615-DNA_G10
```
but this gives me no log or error messages, and no output file at all...

**Comment by jyhehir** [comment]
Hi,

Strange that you have absolutely no error messages.

A typical way to run it would be 

java -Xmx8G -jar MobileInsertions-0.2.1.jar -properties Mobster.properties -in A1_child.bam,A1_father.bam,A1_mother.bam -sn A1_child,A1_father,A1_mother -out A1_trio_mobster

I will update the build for the properties file.

Regards.
Jayne

**Comment by johanneskoester** [comment]
Thanks!

**Comment by jyhehir** [comment]
version 0.2.2 provides many more resources required for Mobster, but you will still need to install Mosaik seperately. Please let me know if there are any more issues

**Comment by johanneskoester** [comment]
Thanks, I'll try!
