### ISSUE TITLE
repetmask format file

### ISSUE THREAD

**Issue by adriludwig** [jyhehir/mobster#58]
Hi! I'm working with Drosophila and I would like to include the repmask file to eliminate the "old" insertions while using Mobster. I noticed that there are two additional columns, bin and id. I was not able to guess what are exactly these columns. Can you give me more information about that? Thanks very much!

**Comment by ramonamerong** [comment]
I am not sure either, but for Mobster only the 'genoName',	'genoStart', 'genoEnd' and 'repFamily' columns are of importance, although they must be the 6,7,8 and 13th column in the repMask file for Mobster to work!

However, Mobster is not designed to use a repeatmask file for another organism, so it is better to filter predictions afterwards yourself.
Also see point 4. and 5. at the bottom of the documentation:
https://jyhehir.github.io/mobster/documentation.html

**Comment by adriludwig** [comment]
Thanks for the information! I was doing some tests, but it seems I'll not be able to use the "real"  Drosophila repmask file to eliminate reference insertions because most of them are not from the 4 TE groups that mobster will look for.
